alias http='python -m SimpleHTTPServer'
alias vi='vim'
alias myip='curl icanhazip.com'
alias cd..='cd ..'
alias cd...='cd ...'
alias cd....='cd ....'
alias cd.....='cd .....'
alias lock='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
